### ISSUE TITLE
Support more flexible backend configurations

### ISSUE THREAD

**Issue by kha-dinh** [kha-dinh/bibli-ls#11]
Now that there are multiple backends, we need to think of a better way to configure multiple libraries.

For now, only a single backend is supported.

```toml
[backend]
backend_type = "zotero_api" # Available backends: "bibfile", "zotero_api"

[backend.bibfile]
bibfiles = ["references.bib"]

[backend.zotero_api]
library_id = "5123456" # Your library ID
library_type = "user" # "user"" or "group"
api_key = "XXXXXXXXXXXXXXXXXXXXXXXX"
```

A better way may be to allow backends with user-defined names. With this, we also need to be careful when merging backends.

```toml
[backend.onlinelib1]
backend_type = "zotero_api"
library_id = "5123456" 
library_type = "user" 
api_key = "XXXXXXXXXXXXXXXXXXXXXXXX"

[backend.onlinelib2]
backend_type = "zotero_api"
library_id = "513371337"
library_type = "group"
api_key = "XXXXXXXXXXXXXXXXXXXXXXXX"

[backend.bibfile1]
backend_type = "bibfile" 
bibfiles = ["references.bib"]

```
